version: "3"
services:
  web:
    build:
      context: postgres-demo
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - postgres
    ports: 
    - 8080:8080
  postgres:
    image: postgres
    environment:
    - POSTGRES_USER=appuser
    - POSTGRES_PASSWORD=mypassword
    - POSTGRES_DB=bluegills
    ports: 
    - 5432:5432
  