version: "3"
services:
  web:
    build:
      context: springboot-starter-app
      dockerfile: web/src/main/docker/Dockerfile
    restart: always
    depends_on:
    - postgres
    ports: 
    - 8080:8080
  api:
    build:
      context: springboot-starter-app
      dockerfile: api/src/main/docker/Dockerfile
    restart: always
    depends_on:
    - postgres
    ports: 
    - 8090:8090
  postgres:
    image: postgres
    environment:
    - POSTGRES_USER=appuser
    - POSTGRES_PASSWORD=mypassword
    - POSTGRES_DB=bluegills
    ports: 
    - 5432:5432
  queue:
    image: rabbitmq:management-alpine
    hostname: message-queue
    ports:
    - 15672:15672
  